#!/usr/bin/env bash

set -e

npm install

# this is a bit of a greedy way of gettting all the files
find . \
  -path ./node_modules -prune \
  -o -name "*.js*" -print \
  | xargs node_modules/.bin/jshint

# including all of node_modules might result in issues
# it's only included for bourbon, and normalize-scss
node_modules/.bin/node-sass \
  --output-style compressed \
  --include-path node_modules \
  public/stylesheets/application.scss \
  > public/stylesheets/application.css

