#!/usr/bin/env bash

set -e

npm install

node_modules/.bin/jshint \
  --exclude node_modules \
  .

# including all of node_modules might result in issues
# it's only included for bourbon, and normalize-scss
node_modules/.bin/node-sass \
  --output-style compressed \
  --include-path node_modules \
  public/stylesheets/application.scss \
  > public/stylesheets/application.css

