on:
  push:
    branches:
    - main

name: Continuous Deployment

jobs:
  ci:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm run-script build
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "devops-bookmarks"
        heroku_email: "scottmuc@gmail.com"
