on:
  push:
    branches:
    - main

name: Continuous Deployment

jobs:
  ci:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm run-script build
